package com.test.awsdemo.model;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "imagesstore")
public class ImageInfo {

    @DynamoDBHashKey(attributeName = "userId")
    @DynamoDBAutoGeneratedKey
    private String userId;
    @DynamoDBAttribute(attributeName = "originalKey")
	private String objectKey;
    @DynamoDBAttribute(attributeName = "originalBucket")
	private String sourceBucket;
    @DynamoDBAttribute(attributeName = "thumbKey")
	private String thumbKey;
    @DynamoDBAttribute(attributeName = "thumbBucket")
	private String destinationBucket;
	private Date createdTimeStamp;
    
    
	public ImageInfo() {
		super();
	}
	
	public ImageInfo(String userId) {
		super();
		this.userId = userId;
	}
	public String getUserId() {
		return userId;
	}
	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getObjectKey() {
		return objectKey;
	}

	public void setObjectKey(String objectKey) {
		this.objectKey = objectKey;
	}

	public String getSourceBucket() {
		return sourceBucket;
	}

	public void setSourceBucket(String sourceBucket) {
		this.sourceBucket = sourceBucket;
	}

	public String getThumbKey() {
		return thumbKey;
	}

	public void setThumbKey(String thumbKey) {
		this.thumbKey = thumbKey;
	}

	public String getDestinationBucket() {
		return destinationBucket;
	}

	public void setDestinationBucket(String destinationBucket) {
		this.destinationBucket = destinationBucket;
	}

	@DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.CREATE)
	public Date getCreatedTimeStamp() {
		return createdTimeStamp;
	}

	public void setCreatedTimeStamp(Date createdTimeStamp) {
		this.createdTimeStamp = createdTimeStamp;
	}

	@Override
	public String toString() {
		return "ImageInfo [userId=" + userId + ", objectKey=" + objectKey + ", sourceBucket=" + sourceBucket
				+ ", thumbKey=" + thumbKey + ", destinationBucket=" + destinationBucket + ", createdTimeStamp="
				+ createdTimeStamp + "]";
	}

	

}
